# Generated by Django 5.0.6 on 2024-05-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_remove_user_bio_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
